---
- name: Add group
  group:
    name: panda
    state: present
- name: Add user
  user:
    name: panda
    shell: /bin/bash
    groups:
      - panda
      - sudo
- name: Set authorized_key to user panda
  authorized_key:
    user: panda
    state: present
    key: "{{ lookup('file', '/home/vagrant/.ssh/authorized_keys') }}"
    
# tasks file for user
